export const ERROR_INVALID_INPUT = 'ERROR_INVALID_INPUT';
export const ERROR_MOMO = 'ERROR_MOMO';
export const ERROR_HEADER = 'ERROR_HEADER';
export const ERROR_INVALID_TOKEN = 'ERROR_INVALID_TOKEN';
export const ERROR_DIFF_MONEY = 'ERROR_DIFF_MONEY';
export const ERROR_DIFF_SIGNATURE = 'ERROR_DIFF_SIGNATURE';
export const ERROR_NULL = 'ERROR_NULL';
